name: Meta Release Big 3

on: [workflow_dispatch]

jobs:
  appimage:
    uses: ./.github/workflows/release-appimage.yml
  mac:
    uses: ./.github/workflows/release-mac.yml
    secrets: inherit
  windows:
    uses: ./.github/workflows/release-windows.yml
